dict1 = {'Supplier Name': 'masb6-sa1@01337.io',
         'Cost': 5,
         'Delivery reliability': 7,
         'Quality': 6,
         'Technology capabilities': 7,
         'Employment practices': 5,
         'Health and safety ': 5,
         'Local communities’ influence': 10,
         'Contractual stakeholders’ influence': 9,
         'Pollution production': 4,
         'Resource consumption': 10,
         'Eco-design': 4,
         'Environmental management system': 5}

dict2 = {'Supplier Name': "masb6-sa2@01337.io",
         'Cost': 7,
         'Delivery reliability': 4,
         'Quality': 5,
         'Technology capabilities': 8,
         'Employment practices': 4,
         'Health and safety ': 2,
         'Local communities’ influence': 8,
         'Contractual stakeholders’ influence': 7,
         'Pollution production': 6,
         'Resource consumption': 6,
         'Eco-design': 5,
         'Environmental management system': 2}

dict3 = {'Supplier Name': 'masb6-sa3@01337.io',
         'Cost': 6,
         'Delivery reliability': 8,
         'Quality': 9,
         'Technology capabilities': 10,
         'Employment practices': 7,
         'Health and safety ': 6,
         'Local communities’ influence': 5,
         'Contractual stakeholders’ influence': 2,
         'Pollution production': 10,
         'Resource consumption': 7,
         'Eco-design': 9,
         'Environmental management system': 8}

dict4 = {'Supplier Name': 'masb6-sa4@01337.io',
         'Cost': 9,
         'Delivery reliability': 10,
         'Quality': 10,
         'Technology capabilities': 3,
         'Employment practices': 3,
         'Health and safety ': 1,
         'Local communities’ influence': 2,
         'Contractual stakeholders’ influence': 6,
         'Pollution production': 5,
         'Resource consumption': 2,
         'Eco-design': 7,
         'Environmental management system': 4}

dict5 = {'Supplier Name': 'masb6-sa5@01337.io',
         'Cost': 2,
         'Delivery reliability': 6,
         'Quality': 4,
         'Technology capabilities': 1,
         'Employment practices': 2,
         'Health and safety ': 7,
         'Local communities’ influence': 1,
         'Contractual stakeholders’ influence': 1,
         'Pollution production': 9,
         'Resource consumption': 8,
         'Eco-design': 10,
         'Environmental management system': 3}

dict6 = {'Supplier Name': 'masb6-sa6@01337.io',
         'Cost': 10,
         'Delivery reliability': 1,
         'Quality': 3,
         'Technology capabilities': 4,
         'Employment practices': 9,
         'Health and safety ': 9,
         'Local communities’ influence': 9,
         'Contractual stakeholders’ influence': 10,
         'Pollution production': 1,
         'Resource consumption': 1,
         'Eco-design': 3,
         'Environmental management system': 7}

dict7 = {'Supplier Name': 'masb6-sa7@01337.io',
         'Cost': 8,
         'Delivery reliability': 5,
         'Quality': 8,
         'Technology capabilities': 6,
         'Employment practices': 8,
         'Health and safety ': 10,
         'Local communities’ influence': 6,
         'Contractual stakeholders’ influence': 3,
         'Pollution production': 7,
         'Resource consumption': 3,
         'Eco-design': 6,
         'Environmental management system': 1}

dict8 = {'Supplier Name': 'masb6-sa8@01337.io',
         'Cost': 3,
         'Delivery reliability': 9,
         'Quality': 7,
         'Technology capabilities': 2,
         'Employment practices': 6,
         'Health and safety ': 3,
         'Local communities’ influence': 3,
         'Contractual stakeholders’ influence': 5,
         'Pollution production': 3,
         'Resource consumption': 9,
         'Eco-design': 2,
         'Environmental management system': 6}

dict9 = {'Supplier Name': 'masb6-sa9@01337.io',
         'Cost': 1,
         'Delivery reliability': 3,
         'Quality': 1,
         'Technology capabilities': 5,
         'Employment practices': 10,
         'Health and safety ': 4,
         'Local communities’ influence': 7,
         'Contractual stakeholders’ influence': 4,
         'Pollution production': 2,
         'Resource consumption': 4,
         'Eco-design': 1,
         'Environmental management system': 9}

dict10 = {'Supplier Name': 'masb6-sa10@01337.io',
          'Cost': 4,
          'Delivery reliability': 2,
          'Quality': 2,
          'Technology capabilities': 9,
          'Employment practices': 1,
          'Health and safety ': 8,
          'Local communities’ influence': 4,
          'Contractual stakeholders’ influence': 8,
          'Pollution production': 8,
          'Resource consumption': 5,
          'Eco-design': 8,
          'Environmental management system': 10}