dict1 = {'Supplier Name': 'masb6-sa1@01337.io',
         'Cost': 8,
         'Delivery reliability': 10,
         'Quality': 6,
         'Technology capabilities': 7,
         'Employment practices': 5,
         'Health and safety ': 5,
         'Local communities’ influence': 10,
         'Contractual stakeholders’ influence': 9,
         'Pollution production': 4,
         'Resource consumption': 10,
         'Eco-design': 4,
         'Environmental management system': 5}

dict2 = {'Supplier Name': "masb6-sa2@01337.io",
         'Cost': 7,
         'Delivery reliability': 4,
         'Quality': 5,
         'Technology capabilities': 8,
         'Employment practices': 4,
         'Health and safety ': 2,
         'Local communities’ influence': 8,
         'Contractual stakeholders’ influence': 7,
         'Pollution production': 6,
         'Resource consumption': 6,
         'Eco-design': 5,
         'Environmental management system': 2}

dict3 = {'Supplier Name': 'masb6-sa3@01337.io',
         'Cost': 6,
         'Delivery reliability': 8,
         'Quality': 9,
         'Technology capabilities': 10,
         'Employment practices': 7,
         'Health and safety ': 6,
         'Local communities’ influence': 5,
         'Contractual stakeholders’ influence': 2,
         'Pollution production': 10,
         'Resource consumption': 7,
         'Eco-design': 9,
         'Environmental management system': 8}

dict4 = {'Supplier Name': 'masb6-sa4@01337.io',
         'Cost': 9,
         'Delivery reliability': 10,
         'Quality': 10,
         'Technology capabilities': 3,
         'Employment practices': 3,
         'Health and safety ': 1,
         'Local communities’ influence': 2,
         'Contractual stakeholders’ influence': 6,
         'Pollution production': 5,
         'Resource consumption': 2,
         'Eco-design': 7,
         'Environmental management system': 4}